"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var persona_1 = require("./persona");
var direccion_1 = require("./direccion");
var mail_1 = require("./mail");
var telefono_1 = require("./telefono");
var direccionUno = new direccion_1.Direccion("Calle Loreto", 23, 2, "A", 23852, "Madrid", "Madrid");
var direccionDos = new direccion_1.Direccion("Calle Verdad", 2, 5, "B", 23345, "Madrid", "Madrid");
var mailUno = new mail_1.Mail("personal", "pacogarcia@gmail.com");
var telefonoUno = new telefono_1.Telefono("fijo", 916548345);
var telefonoDos = new telefono_1.Telefono("movil", 648348976);
var personaUno = new persona_1.Persona('Paco', 'García Pérez', 56, '34599543C', new Date(1967, 4, 12), 'verde', 'hombre', [direccionUno, direccionDos], [mailUno], [telefonoUno, telefonoDos], "Persona agradable que contesta al teléfono siempre");
var direccionTres = new direccion_1.Direccion("Paseo de la Libertad", 15, 8, "D", 22150, "Villaverde", "Madrid");
var direccionCuatro = new direccion_1.Direccion("Calle Carlos 3", 1, 1, "C", 34201, "Salamanca", "Salamanca");
var mailDos = new mail_1.Mail("personal", "martaflores@gmail.com");
var mailTres = new mail_1.Mail("trabajo", "martaf@deysant.com");
var telefonoTres = new telefono_1.Telefono("fijo", 914987945);
var telefonoCuatro = new telefono_1.Telefono("movil", 676626282);
var personaDos = new persona_1.Persona('Marta', 'Flores Diaz', 25, '52003945G', new Date(1998, 9, 20), 'morado', 'mujer', [direccionTres, direccionCuatro], [mailDos, mailTres], [telefonoTres, telefonoCuatro], "Está pensando en adquirir una tercera residencia");
var direccionCinco = new direccion_1.Direccion("Calle Palermo", 5, 3, "B", 31011, "Badajoz", "Extremadura");
var direccionSeis = new direccion_1.Direccion("Calle Sintoniza", 4, 5, "D", 51520, "Valencia", "Valencia");
var mailCuatro = new mail_1.Mail("personal", "cecilio45@gmail.com");
var mailCinco = new mail_1.Mail("trabajo", "ceciliog@pacter.es");
var telefonoCinco = new telefono_1.Telefono("fijo", 916567832);
var telefonoSeis = new telefono_1.Telefono("movil", 634946521);
var personaTres = new persona_1.Persona('Cecilio', 'Guzmán Trillo', 63, '20683789S', new Date(1960, 4, 7), 'rojo', 'hombre', [direccionCinco, direccionSeis], [mailCuatro, mailCinco], [telefonoCinco, telefonoSeis], "No llamar por las mañanas");
console.log("Personas antes de hacer el cambio:");
console.log(personaUno);
console.log(personaDos);
console.log(personaTres);
var agenda = new Array(personaUno, personaDos, personaTres);
var dniABuscar = "20683789S";
var personaAEditar = agenda.find(function (persona) { return persona.dni === dniABuscar; });
var nuevaDireccion = new direccion_1.Direccion("Calle Ferran", 2, 3, "E", 43453, "Zaragoza", "Zaragoza");
var nuevoMail = new mail_1.Mail("trabajo", "cecilio_guzman@ferreterialorty.com");
var nuevoTelefono = new telefono_1.Telefono("fijo", 916776492);
personaAEditar.agregarNuevaDireccion(nuevaDireccion);
personaAEditar.agregarNuevoMail(nuevoMail);
personaAEditar.agregarNuevoTelefono(nuevoTelefono);
console.log("Personas después de hacer el cambio:");
console.log(personaUno);
console.log(personaDos);
console.log(personaTres);
